vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

require("user.launch")
require("user.options")
require("user.keymaps")
require("user.autocmds")
require("user.myline.customline")
-- spec("user.reactive")
-- spec("user.indentscope")
-- spec("user.feline")
-- spec "user.modicator"
-- spec("user.notify")
-- spec "user.winsep"
-- spec("user.tree")
-- spec("user.noice")
-- spec("user.ufo")
spec("user.treesitter")
spec("user.mason")
spec("user.lspconfig")
spec("user.cmp")
spec("user.telescope")
spec("user.diff")
-- spec("user.map")
spec("user.lspkind")
spec("user.fidget")
spec("user.leap")
-- spec("user.lline")
-- spec("user.startup")
spec("user.whichkey")
-- spec("user.lualine")
-- spec("user.linefly")
spec("user.modes")
-- spec("user.rainbows")
spec("user.icns")
spec("user.comment")
spec("user.conform")
-- spec("user.avante")
-- spec("user.specs")
-- spec("user.miniline")
spec("user.harpoon")
-- spec "user.track"
spec("user.autopairs")
-- spec("user.animate")
-- spec "user.alpha"
-- spec("user.starter")
-- spec("user.project")
spec("user.drop")
-- spec("user.heir")
-- spec("user.devicons")
-- spec "user.smoothie"
-- spec("user.minimap")
spec("user.neoscroll")
-- spec("user.biscuits")
spec("user.yanky")
spec("user.colorizer")
-- spec "user.kt"
-- spec("user.twilight")
spec("user.tfm")
spec("user.ktft")
-- spec("user.clean")
-- spec("user.statuscol")

-- spec("user.monokai_pro")
-- spec("user.solarized")
-- spec("user.solarized8")
-- spec("user.dracula")
-- spec("user.bamboo")
-- spec("user.neosol")
-- spec("user.sunburn")
-- spec("user.papercolorslim")
-- spec("user.de")
-- spec("user.catppuccin")
spec("user.tokyonight")
-- spec("user.gruvbox")
-- spec("user.gruvmat")
-- spec("user.miasma")
-- spec("user.newpaper")
-- spec("user.srcery")

-- spec("user.nebulous")
-- spec("user.bogster")
-- spec("user.doom")
-- spec("user.od")
-- spec("user.material")
-- spec("user.darkplus")
-- spec("user.omni")
-- spec("user.darcula")
-- spec("user.snight")
-- spec("user.minihue")
-- spec("user.ayu")
-- spec("user.b16custom")
-- spec("user.yettasty")
-- spec("user.sonokai")
-- spec("user.seoul256")
-- spec("user.rosepine")
-- spec("user.bluloco")
-- spec("user.nord")
-- spec("user.nordic")
-- spec("user.onenord")
-- spec("user.base16")
-- spec("user.gruvbabie46")
-- spec("user.idlefingers")
-- spec("user.colorscheme")
-- spec("user.gaba")
-- spec("user.moonbow")
-- spec("user.codesmell")
-- spec("user.ronny")
-- spec("user.onedarkpro")
-- spec("user.rams")
-- spec("user.1monokai")
-- spec("user.ofirkai")
-- spec("user.citrus")
-- spec("user.kanagawa")
-- spec("user.retro")
-- spec("user.tokyogogh")
-- spec("user.midnight")
-- spec("user.moonfly")
-- spec "user.gitcolours"
-- spec("user.papercolor")
-- spec("user.solshul")
-- spec("user.osaka")
-- spec("user.enfocado")
-- spec("user.tokyodark")
-- spec("user.adwaita")
-- spec("user.tasty")
-- spec("user.sodakai")
-- spec("user.melange")
-- spec("user.horizon")
-- spec("user.horizonv2")
-- spec("user.tender")
-- spec("user.noctis_real")
-- spec("user.moonshine")
-- spec("user.noctis")
-- spec("user.quantum")
-- spec("user.ibmbon")
-- spec("user.molokai")
-- spec("user.base46")
-- spec("user.calvera")
-- spec("user.gruvog")

require("user.lazy")
